python train.py \
--model_name 'transformer' \
--num_epochs 30 \
--high_resolution_frequency 400 \
--data_dir './data/' \
--random_key 1234 \
--train_split 0.7 \
--valid_split 0.15 \
--save_dir 'results/' \
